# Generated by Django 6.0.6 on 2026-06-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_remove_userprofile_user_remove_uploadeddocument_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
