# Generated by Django 6.0.6 on 2026-06-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_uploadeddocument_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='quiz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
