# Generated by Django 6.0.6 on 2026-06-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_uploadeddocument_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
