# Generated by Django 6.0.6 on 2026-06-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_quizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assistant.uploadeddocument'),
        ),
    ]
