# Generated by Django 6.0.6 on 2026-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_alter_quizresult_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='pdf_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
